max_width = 100
hard_tabs = false
tab_spaces = 4
wrap_comments = true
comment_width = 80
normalize_comments = true
merge_imports = false
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
merge_derives = true
use_try_shorthand = true
unstable_features = true

edition = "2018"
